### ISSUE TITLE
Additionally parse Link headers with rel=me

### ISSUE THREAD

**Issue by barnabywalters** [jgarber623/rel-me.cc#127]
Apparently the code does not do this yet (https://github.com/jgarber623/rel-me.cc/blob/main/rel_me_app.rb#L90), and it would be an especially useful feature (headers are harder to manually inspect than markup)

**Comment by jgarber623** [comment]
Following up from @barnabywalters' [original comment in IndieWeb chat](https://chat.indieweb.org/dev/2022-11-07/1667858377272500):

> I assume it parses Link headers as well as markup?

As noted above in `rel_ma_app.rb` [line 90](https://github.com/jgarber623/rel-me.cc/blob/main/rel_me_app.rb#L90), the app currently only looks at `rel="me"` results in markup. It should be fairly straightforward to parse the response's `Link` headers using [link-header-parser](https://rubygems.org/gems/link-header-parser).

Currently, the array of URLs show in the UI is neither sorted nor guaranteed to include only unique values. Since no order is currently implied, I could list `rel="me"` URLs found in `Link` headers first.

Or… get more complicated and add an opt-in on the search form (and corresponding query parmaeter) to include headers in the search. Not sure we need to get that complicated, but it's an option.
